"""
提示词模板模块
包含所有工作流节点使用的提示词模板
"""

from .templates import (
    KEYWORD_GENERATION_PROMPT,
    TOPIC_REFINEMENT_PROMPT,
    CONTENT_FILTER_PROMPT,
    HITPOINT_ANALYSIS_PROMPT,
    CONTENT_GENERATION_PROMPT,
    SYSTEM_PROMPT
)

__all__ = [
    "KEYWORD_GENERATION_PROMPT",
    "TOPIC_REFINEMENT_PROMPT", 
    "CONTENT_FILTER_PROMPT",
    "HITPOINT_ANALYSIS_PROMPT",
    "CONTENT_GENERATION_PROMPT",
    "SYSTEM_PROMPT"
] 